const types =  {
  MUTATION_AUTH_USER: 'MUTATION_AUTH_USER',
  MUTATION_CLEAN_AUTH_DATA: 'MUTATION_CLEAN_AUTH_DATA',

  ACTION_CHECK_EMAIL_EXISTENCE: 'ACTION_CHECK_EMAIL_EXISTENCE',
  ACTION_SIGNUP: 'ACTION_SIGNUP',
  ACTION_SAVE_USER_LOCALLY: 'ACTION_SAVE_USER_LOCALLY',
  ACTION_LOGIN: 'ACTION_LOGIN',
  ACTION_TRY_AUTO_LOGIN: 'ACTION_TRY_AUTO_LOGIN',
  ACTION_LOGOUT: 'ACTION_LOGOUT',
  ACTION_DISPLAY_ERROR: 'ACTION_DISPLAY_ERROR',

  GETTER_USER: 'GETTER_USER',
  GETTER_IS_USER_AUTHENTICATED: 'GETTER_IS_USER_AUTHENTICATED',

};

export default types;